#include "stdafx.h"

#define GAME_TITLE "Test Title"
#define BACKGROUND_COLOR 0xfff000000

#define WINDOW_DEFAULT_WIDTH 1920
#define WINDOW_DEFAULT_HEIGHT 1080
#define WINDOW_START_FULLSCREEN true
#define WINDOW_RESIZABLE false
#define WINDOW_EXIST_MINIMIZEBOX false
#define WINDOW_EXIST_MAXIMIZEBOX false
#define WINDOW_EXIST_CLOSEBOX true

#define INCH_PER_DISTANCE 184
#define DIAGONAL_LENGTH 12